"""Two kinds of HTTP 403, told apart by what they say.

The site's own captcha refusal is always the same page (Apache Sling: "Cannot serve request to /bin/... on this server"): the test FAILS, at once -
waiting cannot make a captcha valid.  Every other 403 / 429 (a firewall or CDN page, a bare "Forbidden", ...) is the WAF: a pause, then the test is run again.
"""
from __future__ import annotations

import time
from types import SimpleNamespace

import pytest
from playwright.async_api import async_playwright

from regrunner.engine.actions import click_and_verify
from regrunner.engine.runner import RunOptions, execute
from regrunner.engine.session import ActionError, is_captcha_refusal
from regrunner.events import EventBus
from tests.site import server as mock_server
from tests.test_page_ready import opened
from tests.workbook_factory import build_steps_workbook

# Copied from a real run (network.jsonl of a UAT run whose captcha was not accepted).
SLING_403 = ('<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html>\n    <head><title>403 Forbidden</title></head>\n    <body>\n        <h1>Forbidden</h1>\n'
             '        <p>Cannot serve request to /bin/policy/detail/cs on this server</p>\n        \n        \n        \n        <hr>\n'
             '        <address>Apache Sling</address>\n    </body>\n</html>\n')
CLOUDFRONT_403 = ('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD>'
                  '<BODY><H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><PRE>Request blocked. We can\'t connect to the server for this app or website '
                  'at this time. Generated by cloudfront (CloudFront)\nRequest ID: 9xLq3p2Zr0fW1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t==</PRE></BODY></HTML>')


@pytest.fixture(autouse=True)
def waf_off():
    mock_server.WAF.update(until=0.0, pages=False, sling=False)
    mock_server.FLAKY.update(block=0, seen=0)
    yield
    mock_server.WAF.update(until=0.0, pages=False, sling=False)
    mock_server.FLAKY.update(block=0, seen=0)


def test_only_the_sites_own_refusal_page_counts_as_the_captcha_being_rejected():
    assert is_captcha_refusal(SLING_403)
    assert is_captcha_refusal(SLING_403.replace("/bin/policy/detail/cs", "/bin/policy/search/cs"))         # the path changes, the page does not
    assert not is_captcha_refusal(CLOUDFRONT_403)                                                           # a reference / request ID: the CDN, so a wait
    assert not is_captcha_refusal("Forbidden")
    assert not is_captcha_refusal("<html><body>Access denied</body></html>")
    assert not is_captcha_refusal('{"message": "Request blocked."}')
    assert not is_captcha_refusal("<h1>Forbidden</h1><address>Apache Sling</address>")                    # half of it is not it
    assert not is_captcha_refusal("<p>Cannot serve request to /x on this server</p>")
    assert not is_captcha_refusal("")


# -- one step ---------------------------------------------------------------------------------------------------------------------
@pytest.mark.browser
async def test_a_servlet_call_refused_with_the_sites_own_page_fails_the_step_as_a_captcha_problem_not_a_block(site):
    async with async_playwright() as pw:
        browser, session, _ = await opened(pw, site, "captcha_refusal.html")
        try:
            await session.ensure_ready()
            res = SimpleNamespace(locator=session.page.locator("#go"))
            ctx = SimpleNamespace(act_timeout_s=6.0, out=SimpleNamespace(notes=[]), session=session)
            mock_server.WAF.update(until=time.time() + 30, sling=True)
            with pytest.raises(ActionError, match=r"captcha"):
                await click_and_verify(ctx, res, lambda: res.locator.evaluate("e => e.click()"))
            assert "Apache Sling" in session.captcha_refusal and "POST" not in session.captcha_refusal and "GET /bin/policy/detail/cs" in session.captcha_refusal
            assert session.block_error == ""                                                              # not a WAF block: nothing to wait out
            assert "recaptchaBypassToken" in session.captcha_refusal and "instead of waiting" in session.captcha_refusal
        finally:
            await session.close()
            await browser.close()


@pytest.mark.browser
async def test_the_same_refusal_with_any_other_body_is_still_a_waf_block(site):
    async with async_playwright() as pw:
        browser, session, _ = await opened(pw, site, "captcha_refusal.html")
        try:
            await session.ensure_ready()
            res = SimpleNamespace(locator=session.page.locator("#go"))
            ctx = SimpleNamespace(act_timeout_s=6.0, out=SimpleNamespace(notes=[]), session=session)
            mock_server.WAF.update(until=time.time() + 30, sling=False)                                       # a bare "Forbidden"
            with pytest.raises(ActionError, match=r"Blocked by the site: HTTP 403 to the GET /bin/policy/detail/cs"):
                await click_and_verify(ctx, res, lambda: res.locator.evaluate("e => e.click()"))
            assert session.captcha_refusal == "" and "WAF" in session.block_error
        finally:
            await session.close()
            await browser.close()


# -- a whole run ------------------------------------------------------------------------------------------------------------------
def flow(sheet) -> None:
    sheet.add("Open", "Open", Value="DT_URL")
    sheet.add("Click", "Click Get Started", FindBy="xpath", FindBy_Value="//button[@id='go']", Index=0)
    sheet.add("Output", "Heading", FindBy="xpath", FindBy_Value="//h1", Index=0, Output_Property="innertext")
    sheet.add("Quit", "Quit")


async def run_the_flow(site, make_cfg, tmp_path):
    wb = tmp_path / "wb.xlsx"
    build_steps_workbook(wb, {"Start": flow}, params={"Start": {"DT_URL": site + "captcha_refusal.html"}})
    events: list[dict] = []
    bus = EventBus()
    bus.subscribe(events.append)
    conf = make_cfg(**{"runner.stagger_s": 0, "runner.min_page_load_gap_s": 0, "runner.block_cooldown_s": 1.5, "runner.block_retries": 2})
    result = await execute(RunOptions(workbook=wb, seed=1, tests=["Start"], workers=1), conf, bus)
    return result.tests[0], events


@pytest.mark.browser
async def test_a_run_whose_captcha_is_refused_fails_at_once_without_pausing_or_running_the_test_again(site, make_cfg, tmp_path):
    mock_server.WAF.update(until=time.time() + 120, sling=True)
    test, events = await run_the_flow(site, make_cfg, tmp_path)
    assert test.status == "FAILED" and test.attempt == 1 and not test.attempts and not test.blocked
    assert "captcha" in test.error.lower() and "Apache Sling" in test.error
    assert [s.status for s in test.steps][:2] == ["PASSED", "FAILED"] and test.skipped >= 1                   # it stopped there: nothing after it can be trusted
    assert not [e for e in events if e["type"] == "run_paused"]                                               # no cool-down, no worker taken out of service


@pytest.mark.browser
async def test_a_run_blocked_by_a_waf_still_pauses_and_runs_the_test_again(site, make_cfg, tmp_path):
    mock_server.WAF.update(until=time.time() + 4, sling=False)                                                 # blocked for a few seconds, then let in
    test, events = await run_the_flow(site, make_cfg, tmp_path)
    assert test.attempt >= 2 and test.attempts and test.attempts[0]["blocked"]
    assert [e for e in events if e["type"] == "run_paused"]


def open_only(sheet) -> None:
    sheet.add("Open", "Open", Value="DT_URL")
    sheet.add("Quit", "Quit")


@pytest.mark.browser
@pytest.mark.parametrize("sling, waits", [(True, False), (False, True)])
async def test_a_page_load_refused_with_the_sites_own_page_fails_but_any_other_403_still_waits(site, make_cfg, tmp_path, sling, waits):
    mock_server.WAF.update(sling=sling)
    mock_server.FLAKY.update(block=1, seen=0)                                                                  # the first load of the page is refused
    wb = tmp_path / "wb.xlsx"
    build_steps_workbook(wb, {"Start": open_only}, params={"Start": {"DT_URL": site + "flaky/captcha_refusal.html"}})
    events: list[dict] = []
    bus = EventBus()
    bus.subscribe(events.append)
    conf = make_cfg(**{"runner.stagger_s": 0, "runner.min_page_load_gap_s": 0, "runner.block_cooldown_s": 1, "runner.block_retries": 2})
    result = await execute(RunOptions(workbook=wb, seed=1, tests=["Start"], workers=1), conf, bus)
    test = result.tests[0]
    paused = [e for e in events if e["type"] == "run_paused"]
    if waits:                                                                                                  # a bare 403: pause, run again, and it passes
        assert paused and test.status == "PASSED" and test.attempt == 2
    else:                                                                                                      # the site's own captcha page: a failure, nothing waited for
        assert not paused and test.attempt == 1 and not test.blocked and test.status in ("FAILED", "ERROR")
        assert "captcha" in test.error.lower()
